//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFModernVerticalMenu.Classes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProduct { get; set; }
        public string Name { get; set; }
        public Nullable<int> Count { get; set; }
        public string Image { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> idRoom { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
