//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFModernVerticalMenu.Classes.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public int idOperation { get; set; }
        public Nullable<int> idProduct { get; set; }
        public string Date { get; set; }
        public Nullable<int> idClient { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Room Room { get; set; }
    }
}
